services:
  backend:
    build:
      context: .
      dockerfile: backend/BookSearchApi/Dockerfile
    ports:
      - "5074:5074"
    environment:
      ASPNETCORE_URLS: http://+:5074
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"


networks:
  app-net:
